### ISSUE TITLE
How to combine node-delayed-request with node-request-retry ?

### ISSUE THREAD

**Issue by marcolino** [leeroybrun/node-delayed-request#1]
I need to combine node-request-retry (https://github.com/FGRibreau/node-request-retry) module with node-delayed-request (this module), since I need to place delayed requests, and to be able to retry the request in case it fail.
Which strategy would you suggest ?
Should I fork this module, changing the dependency from 'request' to 'request-retry' ? Do you think this could possibly work? Or should I better do the reverse, forking 'request-retry' changing the dependency from 'request' to 'delayed-request' ?
Or should I make an entirely new module, manually integrating the two ?
Otherwise, do you have some cleverer alternative idea?
Thanks in advance!

**Comment by dqr79** [comment]
"Should I fork this module, changing the dependency from 'request' to 'request-retry'?" - this is what I did, so far it seems to work fine

**Comment by leeroybrun** [comment]
Forking the module and changing the dependency looks fine to me.

Maybe we should find a way to easily combine request modules, without the need to fork them, but for now I have no idea how to do it...

**Comment by leeroybrun** [comment]
Solved with #2 .
